---
framework: mocha
preRun:
     command:
        - npm install
preMerge:
  pattern:
    - "./test/unit/**/*.test.js"
postMerge:
  pattern: 
    - "./test/unit/**/*.test.js"
postRun:
     command:
        - node --version
version: 1.0
